[server]
headless = true
maxUploadSize = 500
enableXsrfProtection = false
maxMessageSize = 500

[theme]
primaryColor = "#0f766e"
backgroundColor = "#f6fbf9"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"